name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: "check"
          src: "rocketwatch sentinel"
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          src: "rocketwatch sentinel"
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --extra dev
      - run: uv sync --extra dev
        working-directory: sentinel
      - run: uv run mypy rocketwatch/
      - run: uv run mypy .
        working-directory: sentinel
