name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "check"
          src: "rocketwatch sentinel"
      - uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "format --check"
          src: "rocketwatch sentinel"
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv run --group dev mypy rocketwatch/
      - run: uv run --project sentinel --group dev mypy sentinel/
