name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8
      - run: uv run --group test pytest --cov=rocketwatch --cov-report=term-missing --cov-report=xml
      - uses: codecov/codecov-action@v6
        with:
          files: coverage.xml
